POST http://127.0.0.1:8000/api/signup 
Content-Type: application/json

{ "email": "john.doe@example.com", "first_name": "John", "last_name": "Doe" }

###

POST http://127.0.0.1:8000/api/login 
Content-Type: application/json

{ "username": "aaa2", "password": "aaa" }

###

GET http://127.0.0.1:8000/api/test_token 
Content-Type: application/json
Authorization: token ea1273e90143c63457bcaa1343ece4b251d81287