# Generated by Django 5.0.2 on 2024-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bacheloraapp", "0002_initial_datta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
